CREATE DATABASE CableTV;

USE CableTV;

CREATE TABLE Customer (
	Id INT AUTO_INCREMENT,
	Name VARCHAR(250), 
	Phone_Number VARCHAR(20), 
	Email_Id	VARCHAR(100), 
	Address VARCHAR(250), 
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_Customer PRIMARY KEY (Id));

CREATE TABLE Employee (
	Id INT AUTO_INCREMENT,
	Name VARCHAR(250),
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_Employee PRIMARY KEY (Id));
	
CREATE TABLE Connection (
	Id INT AUTO_INCREMENT,
	Customer_Id	INT,
	Opening_Date TIMESTAMP,
	Deposite_Amount DOUBLE(20,2),
	Created_By INT,
	Closing_Date	TIMESTAMP,
	Deposite_Refund_Amound DOUBLE(20,2),
	Closed_By INT,
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_Connection PRIMARY KEY (Id),
	CONSTRAINT FK_Conn_CreatedBy_Emp FOREIGN KEY (Created_By) REFERENCES Employee(Id),
	CONSTRAINT FK_Conn_ClosedBy_Emp FOREIGN KEY (Closed_By) REFERENCES Employee(Id));

CREATE TABLE Charge	(
	Id INT AUTO_INCREMENT,
	MMYY VARCHAR(20),
	Charge DOUBLE(20,2),
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_Charge PRIMARY KEY (Id));
	
CREATE TABLE Transaction (
	Id INT AUTO_INCREMENT,
	Customer_Id	INT,
	Amount DOUBLE(20,2),
	Recevied_By INT,
	Recevied_From VARCHAR(250),
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_Transaction PRIMARY KEY (Id),
	CONSTRAINT FK_Trans_RecvBy_Emp FOREIGN KEY (Recevied_By) REFERENCES Employee(Id));

CREATE TABLE ConnectionChargeTransaction (
	Id INT AUTO_INCREMENT,
	Connection_Id INT,
	Charge_Id INT,
	Transaction_Id INT,
	Paid_Amount DOUBLE(20,2),
	Last_Update_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_CCT PRIMARY KEY (Id),
	CONSTRAINT FK_CCT_ConnId_Conn FOREIGN KEY (Connection_Id) REFERENCES Connection(Id),
	CONSTRAINT FK_CCT_ConnId_Chrg FOREIGN KEY (Charge_Id) REFERENCES Charge(Id),
	CONSTRAINT FK_CCT_ConnId_Trans FOREIGN KEY (Transaction_Id) REFERENCES Transaction(Id));
	
--Insert into cabletv.customer (Name, Phone_Number, Email_Id, Address) VALUES ('Harish' , '9003369782', 'harish_sci@hotmail.com','153 N.K.Ganapathy Street Anna Nagar')